version: '3'
services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    env_file: .env
    ports:
      - ${MONGODB_PORT}:27017
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_INITDB_ROOT_USERNAME}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_INITDB_ROOT_PASSWORD}
    volumes:
      - type: bind
        source: ./data
        target: /data/db